<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Ruslans-MacBook-Pro.local" failures="1" tests="1" name="Failure Test" time="0.008" errors="0" timestamp="2023-08-31T01:01:48 EEST">
  <testcase classname="testcases.TestFailure" name="doLogin" time="0.001">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testcases.TestFailure.doLogin(TestFailure.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- doLogin -->
</testsuite> <!-- Failure Test -->
